stages:
  preprocess:
    cmd: python src/data/preprocess.py
    deps:
      - data/raw/telco_customer_churn.csv
      - src/data/preprocess.py
    outs:
      - data/processed/cleaned_telco.csv


  train:
    cmd: python src/models/train.py
    deps:
      - data/processed/cleaned_telco.csv
      - src/models/train.py
    outs:
      - model.pkl
